Repository grimme-lab/MindlessGen, pull requests merged in 2024-11, with the labels that each got.

#72 Update Docs
  .github/CODEOWNERS
  CHANGELOG.md
  README.md
  mindlessgen.toml
  pyproject.toml
  src/mindlessgen/prog/config.py
  test/test_config/test_config_set_attributes.py
  test/test_molecules/test_refinement.py
Labels: documentation

#78 Fix random number generation by removing legacy random number generation
  CHANGELOG.md
  src/mindlessgen/molecules/generate_molecule.py
  src/mindlessgen/molecules/miscellaneous.py
  src/mindlessgen/molecules/molecule.py
Labels: bug

#79 Remove deprecated tests that are not strictly true
  test/conftest.py
  test/test_generate/test_generate_molecule.py
Labels: bug

#73 A fixed molecular charge for the molecule generation.
  CHANGELOG.md
  mindlessgen.toml
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/generate_molecule.py
  src/mindlessgen/molecules/miscellaneous.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/xtb.py
  test/test_config/test_config_set_attributes.py
  test/test_generate/test_generate_molecule.py
  test/test_molecules/test_miscellaneous.py
  test/test_molecules/test_refinement.py
Labels: enhancement

#81 `atlist` to `ati` and back conversion
  src/mindlessgen/molecules/__init__.py
  src/mindlessgen/molecules/molecule.py
  test/test_molecules/test_molecule.py
Labels: enhancement

#82 Update `CODEOWNERS`
  .github/CODEOWNERS
Labels: repository

#74 The `.UHF` file is now written if the molecule has a uhf larger than 0
  src/mindlessgen/molecules/molecule.py
Labels: data-processing

#84 Merge latest `mindlessgen` features into `gp3_ipea`
  .github/CODEOWNERS
  CHANGELOG.md
  README.md
  mindlessgen.toml
  pyproject.toml
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/__init__.py
  src/mindlessgen/molecules/generate_molecule.py
  src/mindlessgen/molecules/miscellaneous.py
  src/mindlessgen/molecules/molecule.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/xtb.py
  test/conftest.py
  test/test_config/test_config_set_attributes.py
  test/test_generate/test_generate_molecule.py
  test/test_molecules/test_miscellaneous.py
  test/test_molecules/test_molecule.py
  test/test_molecules/test_refinement.py
Labels: enhancement
