Repository grimme-lab/MindlessGen, pull requests merged in 2024-10, with the labels that each got.

#51 Implemented the van der Waals radii inside the check distance function
  CHANGELOG.md
  mindlessgen.toml
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/molecules/generate_molecule.py
  src/mindlessgen/prog/config.py
  test/fixtures/example_config.toml
  test/test_config/test_config_set_attributes.py
  test/test_config/test_load_from_toml.py
  test/test_generate/test_generate_molecule.py
Labels: enhancement

#52 IP/EA checks with g-xTB as an additional post-processing step
  src/mindlessgen/generator/main.py
  src/mindlessgen/prog/config.py
Labels: development

#58 An update in the ReadMe.md to be more specific with the element composition function.
  CHANGELOG.md
  README.md
  mindlessgen.toml
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/molecules/generate_molecule.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/config.py
Labels: documentation

#60 Changed the uhf value when xtb calculates with lanthanides
  CHANGELOG.md
  src/mindlessgen/qm/xtb.py
Labels: bug

#62 Elements 87 to 103 are now accessible via the `element composition`
  CHANGELOG.md
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/miscellaneous.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/xtb.py
  test/test_molecules/test_miscellaneous.py
Labels: enhancement

#65 Bunch of technical fixes
  README.md
  src/mindlessgen/molecules/__init__.py
  src/mindlessgen/molecules/molecule.py
  src/mindlessgen/qm/orca.py
  src/mindlessgen/qm/xtb.py
Labels: bug

#69 Fix bug with Lr leading to an
  CHANGELOG.md
  src/mindlessgen/molecules/generate_molecule.py
  src/mindlessgen/molecules/molecule.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/config.py
  test/test_generate/test_generate_molecule.py
Labels: bug
