Repository grimme-lab/MindlessGen, pull requests merged in 2024-09, with the labels that each got.

#28 Better defaults, config description and CI check skips
  .github/workflows/ci.yml
  mindlessgen.toml
Labels: documentation, build

#32 Fix `test_iterative_optimization`
  src/mindlessgen/molecules/molecule.py
  test/fixtures/C2H1N2O1Co1Ge2Ta1Hg1_frag.CHRG
  test/fixtures/C2H1N2O1Co1Ge2Ta1Hg1_frag.UHF
  test/fixtures/C2H1N2O1Co1Ge2Ta1Hg1_frag.xyz
  test/fixtures/C2H2N2O1Co1Ge2Ta1Hg1.CHRG
  test/fixtures/C2H2N2O1Co1Ge2Ta1Hg1.UHF
  test/fixtures/C2H2N2O1Co1Ge2Ta1Hg1.xyz
  test/test_molecules/test_molecule.py
  test/test_molecules/test_refinement.py
Labels: bug

#34 introduce more general fragmentation test
  test/fixtures/C13H14.xyz
  test/fixtures/C7H8.xyz
  test/test_molecules/test_refinement.py
  test/test_qm/test_xtb.py
Labels: bug, invalid

#35 GFN level now accessible
  CHANGELOG.md
  mindlessgen.toml
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/xtb.py
Labels: enhancement

#37 Append to 'mindless.molecules' and better printout per molecule
  src/mindlessgen/cli/entrypoint.py
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/molecule.py
Labels: bug, enhancement

#38 Add release workflow
  .github/workflows/release.yml
Labels: build

#40 Prepare `v0.4.0` release
  CHANGELOG.md
  pyproject.toml
Labels: build

#41 Include PyPi installation into `README.md` and re-structure it
  README.md
Labels: documentation

#45 Make scaling factor for van-der-Waals radii for fragment detection adjustable
  CHANGELOG.md
  mindlessgen.toml
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/molecules/molecule.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/config.py
  test/test_molecules/test_refinement.py
Labels: bug, algorithm

#49 Add support for the new "g-xTB" method (working title: GP3-xTB) and minor bug fixes
  CHANGELOG.md
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/postprocess.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/__init__.py
  src/mindlessgen/qm/gp3.py
  src/mindlessgen/qm/xtb.py
Labels: bug, enhancement
