Repository grimme-lab/MindlessGen, pull requests merged in 2025-01, with the labels that each got.

#100 Element composition dict with str and mixed keys
  CHANGELOG.md
  README.md
  src/mindlessgen/prog/config.py
  test/test_generate/test_generate_molecule.py
Labels: enhancement, code-standard

#103 Rename `gp3` to `gxtb`
  src/mindlessgen/generator/main.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/__init__.py
  src/mindlessgen/qm/gxtb.py
Labels: code-standard

#104 `GXTBConfig`
  CHANGELOG.md
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/postprocess.py
  src/mindlessgen/prog/__init__.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/gxtb.py
Labels: enhancement

#101 Added support for Turbomole
  CHANGELOG.md
  mindlessgen.toml
  pyproject.toml
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/molecule.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/__init__.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/__init__.py
  src/mindlessgen/qm/tm.py
  test/test_molecules/test_molecule.py
Labels: algorithm

#108 New parallelization
  .github/CODEOWNERS
  CHANGELOG.md
  environment.yml
  mindlessgen.toml
  pyproject.toml
  src/mindlessgen/generator/main.py
  src/mindlessgen/molecules/postprocess.py
  src/mindlessgen/molecules/refinement.py
  src/mindlessgen/prog/__init__.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/prog/parallel.py
  src/mindlessgen/qm/base.py
  src/mindlessgen/qm/gxtb.py
  src/mindlessgen/qm/orca.py
  src/mindlessgen/qm/tm.py
  src/mindlessgen/qm/xtb.py
  test/test_molecules/test_refinement.py
  test/test_qm/test_xtb.py
Labels: enhancement, algorithm

#110 update `environment.yaml` and format file
  environment.yml
  src/mindlessgen/generator/main.py
Labels: build, code-standard

#111 Dev/sym opt
  CHANGELOG.md
  mindlessgen.toml
  src/mindlessgen/cli/cli_parser.py
  src/mindlessgen/generator/main.py
  src/mindlessgen/prog/__init__.py
  src/mindlessgen/prog/config.py
  src/mindlessgen/qm/tm.py
  src/mindlessgen/symmetrization/__init__.py
  src/mindlessgen/symmetrization/base.py
  src/mindlessgen/symmetrization/inversion.py
  src/mindlessgen/symmetrization/mirror.py
  src/mindlessgen/symmetrization/rotation.py
  test/test_Structure_modification/__init__.py
  test/test_Structure_modification/test_inversion.py
  test/test_Structure_modification/test_mirror.py
  test/test_Structure_modification/test_rotation.py
Labels: algorithm

#118 More significant digits for coordinate files (`coord` and `*.xyz`)
  CHANGELOG.md
  src/mindlessgen/molecules/molecule.py
  test/test_molecules/test_molecule.py
Labels: bug, interface
